version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Authorization-Workshop"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: jQuery
    versions:
    - 3.5.1
